FROM ruby:2.7.1-alpine3.11

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
COPY . $APP_HOME

RUN apk update --no-cache \
    && apk upgrade --no-cache \
    && apk add --update --no-cache --virtual .ruby-builddeps build-base \
    && bundle install \
    && apk del build-base

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
