FROM ruby:2.7.1-alpine3.11

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
COPY . $APP_HOME

RUN apk update --no-cache \
    && apk upgrade --no-cache \
    && apk add --update --no-cache --virtual .ruby-builddeps build-base \
    && bundle install \
    && apk del build-base

ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments

CMD ["puma"]
