version: '3.3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - '24224:24224'
      - '24224:24224/udp'

  elasticsearch:
    image: elasticsearch:7.6.2
    environment:
      - 'discovery.type=single-node'
    expose:
      - 9200
    ports:
      - '9200:9200'

  kibana:
    image: kibana:7.6.2
    ports:
      - '5601:5601'

  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
    networks:
      - front_net
      - back_net

networks:
  back_net:
  front_net:
