{
 "title": "xyiboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Env", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "ui rq 95 p",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le))"
    },
    {
     "expr": "ui_request_count{namespace=~\"namespace\"}"
    }
   ]
  },
  {
   "title": "ui http rq w err",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"[45].*\"}[1m])"
    }
   ]
  },
  {
   "title": "ui http rq",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{job=\"ui\"}[1m])"
    }
   ]
  }
 ]
}